/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "ui-background": "var(--ui-background)",
        "ui-border": "var(--ui-border)",
        "ui-surface-high": "var(--ui-surface-high)",
        "deep-navy": "var(--deep-navy)",
        "surface-dark": "var(--surface-dark)",
        "surface-card": "var(--surface-card)",
        "secondary-brand": "#3B82F6",
        "secondary-container": "#60A5FA",
        "status-pass": "#34D399",
        "status-warning": "#F59E0B",
        "status-fail": "#F87171",
        "status-info": "#94A3B8",
        "surface-tint": "#8B93A7",
        "primary": "var(--primary)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        // Cyberpunk HUD Colors
        "cyber-void": "#030712",
        "cyber-dark": "#060B18",
        "cyber-surface": "#0B132B",
        "cyber-cyan": "#00F0FF",
        "cyber-matrix": "#39FF14",
        "cyber-amber": "#FFB703",
        "cyber-crimson": "#FF0055",
        "cyber-magenta": "#FF007F",
        "cyber-violet": "#8A2BE2",
      },
      boxShadow: {
        "neon-cyan": "0 0 15px rgba(0, 240, 255, 0.45)",
        "neon-matrix": "0 0 15px rgba(57, 255, 20, 0.45)",
        "neon-crimson": "0 0 15px rgba(255, 0, 85, 0.45)",
        "neon-amber": "0 0 15px rgba(255, 183, 3, 0.45)",
        "holo-glow": "0 0 30px rgba(0, 240, 255, 0.25), inset 0 0 15px rgba(0, 240, 255, 0.08)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        headline: ["IBM Plex Sans", "Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
    },
  },
  plugins: [],
};
